### ISSUE TITLE
Составить список параметров, которые нужно будет варьировать

### ISSUE THREAD

**Issue by kalnin-a-i** [kalnin-a-i/pyVCT#1]
Составить точный список тех парметров модели Поттса в коды Нины, которые необходимы будет варьировать при валидации модели. Так  же список тех парметров которые нужно менять для комфортной работы, например число клеток и процент фибробластов. Желательно указать в каком заголовочном файле этот праметр объявляется и в каком файле встречается.

**Comment by berezhnoyac** [comment]
[parameters_loc.txt](https://github.com/kalnin-a-i/pyVCT/files/9835837/parameters_loc.txt)
