### ISSUE TITLE
Переписать функции принимающие арументы из cfg файлов

### ISSUE THREAD

**Issue by kalnin-a-i** [kalnin-a-i/pyVCT#2]
Переписать все функции в файле CPM_dH.c  и если есть в остальых  файлах, таким образом чтобы все переменные, которые перечислены в файле тут #1  ниже, были не константами а принимались как входные аргументы фунцкий. Файл cpmfem.c пока не трогаем. Для этого issue создайть отдельную ветку.

**Comment by violinist2802** [comment]
[variables.txt](https://github.com/kalnin-a-i/pyVCT/files/9894008/variables.txt)
Список переменных, которые задаются в файле def.h через переменные из #1 . Их нельзя пихать во входные аргументы функций, пока они объявлены в def.h через другие константы. То есть значения как аргументы запихивать можно, а в виде переменной нельзя. (Например функция использует NVX, но написать double NVX в аругментах функции нельзя, т.к. на NVX есть ссылка #define в файле def.h)

**Comment by kalnin-a-i** [comment]
Вадим красавчик, всё по кайфу сделал

**Comment by kalnin-a-i** [comment]
Дальше я добью
