### ISSUE TITLE
Составить yaml файл с параметрами

### ISSUE THREAD

**Issue by kalnin-a-i** [kalnin-a-i/pyVCT#3]
Составить yaml файл с параметрами модели, перечисленными в парметрах функции cpmfem. Файл должен иметь вид 
neonatal_rat:
    monolayer_on_fiber:
        param: value
        .
        .
        .
    monolayer_without_fibers:
        param: value
и так по все сценфрям компиляции которые есть в оригинальном репозитории
Поместить файл в одельную папку  conf. Старую можно удалить.

**Comment by violinist2802** [comment]
[config.txt](https://github.com/kalnin-a-i/pyVCT/files/9921260/config.txt)
Переименовать в .yaml

**Comment by zlayapechenushka** [comment]
@violinist2802 сделай такой же порядок параметров как в сетапе, @kalnin-a-i сказал
и вообще надо PR делать!!!!!!!

**Comment by kalnin-a-i** [comment]
Пока работу с конфигаи сворачиваем
